#!/usr/bin/tclsh

# Usage:
# makeDistribution.tcl [<bin dir> [<tag name>] [<type of distribution = "dev" or "user">]]
# <bin dir> is the directory where the script will try to find the compiled executables, 
#           relative to petaverse base dir. Default is "bin", Ie, it will try to find binaries
#           under {petaverse base dir}/bin
# 
# <tag name> is a tag it will use to name the distribution. Default is <svn revision number>.
# <type of distribution> select the type of config file will be copy. .
# 
# This script will copy all the relevant files into {petaverse base dir}/dist/<tag name>

#pdh stands for Project Directory From Here
set pdh "../../"

set binDir "bin" 
set tag ""

# typedist = dev | user
set type_dist "dev"

if {[llength $argv] > 0} {
    set binDir [lindex $argv 0] 
    if {[llength $argv] > 1} {
        set tag [lindex $argv 1]
    }
    if {[llength $argv] > 2} {
        set type_dist [lindex $argv 2]
    }
} 

set binDirH $pdh$binDir

set flist [list  \
$binDirH/opencog/embodiment/Control/MessagingSystem/router \
$binDirH/opencog/embodiment/Control/MessagingSystem/spawner \
$binDirH/opencog/embodiment/Control/OperationalPetController/opc \
$binDirH/opencog/embodiment/Control/OperationalPetController/opcHcTester \
$binDirH/opencog/embodiment/Control/Procedure/combo_shell \
$binDirH/opencog/embodiment/Control/Procedure/combo_shell_stdio \
$binDirH/opencog/embodiment/Learning/LearningServer/learningServer \
$binDirH/opencog/embodiment/RuleValidation/Processor/ruleProcessor \
./killpb.csh \
./cleanup.csh \
./pb.csh \
./pvpInterface.csh \
./run_opc_hc_test.sh \
./stdlib.combo \
./rules_preconditions.combo \
./rules_preconditions.combo-select \
./rules_action_schemata.combo \
$pdh/opencog/embodiment/rules_core.lua \
$pdh/opencog/embodiment/humanoid_rules.lua \
$pdh/opencog/embodiment/humanoid_traits_maria.lua \
$pdh/opencog/embodiment/pet_rules.lua \
$pdh/opencog/embodiment/pet_traits_bob.lua \
$pdh/opencog/embodiment/pet_traits_diablo.lua \
$pdh/opencog/embodiment/pet_traits_maxie.lua \
$pdh/opencog/embodiment/pet_traits_princess.lua \
$pdh/opencog/embodiment/pet_traits_sleepy.lua \
$pdh/opencog/embodiment/RuleValidation/VirtualWorldData/VirtualWorld.xsd \
$pdh/opencog/embodiment/RuleValidation/Processor/validation_core.lua \
./SPCTools.py \
$pdh/opencog/embodiment/frames2relex.rules \
$pdh/opencog/embodiment/frames.list \
$pdh/opencog/embodiment/framesInheritance.list \
]

set schemeOpencogFiles [list \
$pdh/opencog/scm/type_constructors.scm \
$pdh/opencog/scm/utilities.scm \
$pdh/opencog/scm/file-utils.scm \
$pdh/opencog/scm/persistence.scm \
$pdh/opencog/scm/debug.scm \
]

set schemeEmbodimentFiles [list \
$pdh/opencog/embodiment/scm/predicates-frames.scm \
$pdh/opencog/embodiment/scm/language-comprehension.scm \
$pdh/opencog/embodiment/scm/reference-resolution-rules.scm \
$pdh/opencog/embodiment/scm/command-resolution-rules.scm \
$pdh/opencog/embodiment/scm/question-answering.scm \
]

if {$type_dist == "dev"} {
    set flistconfig [list \
    $pdh/opencog/embodiment/dev_config/embodiment.conf \
    $binDirH/opencog/embodiment/AutomatedSystemTest/pbTester \
    $pdh/opencog/embodiment/AutomatedSystemTest/GoldenStandardFiles/gsfile_0.txt \
    $pdh/opencog/embodiment/AutomatedSystemTest/GoldenStandardFiles/gsfile_1.txt \
    $pdh/opencog/embodiment/AutomatedSystemTest/GoldenStandardFiles/gsfile_2.txt \
    $pdh/opencog/embodiment/AutomatedSystemTest/test.conf \
    run_system_test.sh \
    ]
} elseif {$type_dist == "user"} {
    set flistconfig [list \
    $pdh/opencog/embodiment/embodiment.conf \
    ]
}

if {$tag == ""} {
    set tag [lindex [split [exec svn update] " ."] end-1]
}
set distDir [format "$pdh/dist/%s" $tag]
puts "Putting distribution files into $distDir"

exec mkdir -p $distDir
exec mkdir -p $distDir/data

foreach file $flist {
    exec cp -r $file $distDir
}

foreach file $flistconfig {
    exec cp -r $file $distDir
}


# copy scheme sripts
exec mkdir -p $distDir/scm
exec mkdir -p $distDir/scm/embodiment

foreach file $schemeOpencogFiles {
    exec cp $file $distDir/scm/
}

foreach file $schemeEmbodimentFiles {
    exec cp $file $distDir/scm/embodiment/
}
