(ConceptNode "bat")
(ConceptNode "man")

(SimilarityLink (stv 1.0 1.0)
    (ConceptNode "bat")
    (ConceptNode "flying_thing")
)
(SimilarityLink (stv 1.0 1.0)
    (ConceptNode "bat")
    (ConceptNode "blood_drinker")
)


(SimilarityLink (stv 1.0 1.0)
    (ConceptNode "man")
    (ConceptNode "two_leg_creatures")
)
(SimilarityLink (stv 0 0)
    (ConceptNode "man")
    (ConceptNode "blood_drinker")
)
