CUDAROOT = /usr/local/cuda
NVCC = $(CUDAROOT)/bin/nvcc

INCLUDE = include

NVCCFLAGS = -arch=compute_30 -lm

all: kerneltest destin

destin:
	$(NVCC) -I$(INCLUDE) $(NVCCFLAGS) -o bin/destin src/node.cu src/destin.cu src/main.cu

kerneltest:
	$(NVCC) -I$(INCLUDE) $(NVCCFLAGS) -o bin/kerneltest src/node.cu src/destin.cu src/kerneltest.cu

clean:
	rm bin/* 
