.\"                                      Hey, EMACS: -*- nroff -*-
.\" Man page for feature-seection
.\"
.\" Copyright (C) 2012 Linas Vepstas
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.pc
.TH MOSES 1 "April 17, 2012"
.LO 1
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
feature-selection \- blah blah blah
.SH SYNOPSIS
.\" The help & version command line
.B moses
.RB \-h | \--help
.br
.B moses
.RB \--version
.br
.\" The general command line
.B moses
.RB [ \-A
.IR max_score ]
.RB [ \-a
.IR algo ]
.SH DESCRIPTION
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBfeature-selection\fP is the command-line blah ...
.PP
.\" ============================================================
.SH EXAMPLE

.PP
.\" ============================================================
.SH OVERVIEW
\fBfeature-selection\fP implements blah

.PP
.\" ============================================================
.SH OPTIONS
.PP
Options blah blah fall into four classes: those for specifying inputs,
controlling operation, printing output, and running
\fBmoses\fP in demo mode.

.SS "General options"
.TP
.BI \-e\  exemplar
Specify an initial \fIexemplar\fR to use. Each exemplar is written in
combo. May be specified multiple times.
.TP
.B \-h, \-\-help
Print help.
.PP
.\" ============================================================
.SH TODO
write this man page

.SH SEE ALSO
.br
More information is available at
.B http://wiki.opencog.org/w/MOSES
.SH AUTHORS
.nh
\fBfeature-selection\fP was written by Nil Geisweiller.
.PP
This manual page is being written by Linas Vepstas. It is INCOMPLETE.
