# - Try to find the ubigraphclient library; Once done this will define
#
#  UBIGRAPHCLIENT_FOUND - system has the ubigraphclient library
#  UBIGRAPHCLIENT_INCLUDE_DIRS - the ubigraphclient include directory
#  UBIGRAPHCLIENT_LIBRARIES - The libraries needed to use ubigraphclient

# Copyright (c) 2008, OpenCog.org (http://opencog.org)
#
# Redistribution and use is allowed according to the terms of the BSD license.
# For details see the accompanying COPYING-CMAKE-SCRIPTS file.

# Look for the header file
FIND_PATH(UBIGRAPHCLIENT_INCLUDE_DIR UbigraphAPI.h)

# Look for the library
FIND_LIBRARY(UBIGRAPHCLIENT_LIBRARY NAMES ubigraphclient PATH /usr/lib 
	/usr/local/lib /opt/local/lib)

# Copy the results to the output variables.
IF(UBIGRAPHCLIENT_INCLUDE_DIR AND UBIGRAPHCLIENT_LIBRARY)
	SET(UBIGRAPHCLIENT_FOUND 1)
	SET(UBIGRAPHCLIENT_LIBRARIES ${UBIGRAPHCLIENT_LIBRARY})
	SET(UBIGRAPHCLIENT_INCLUDE_DIRS ${UBIGRAPHCLIENT_INCLUDE_DIR})
ELSE(UBIGRAPHCLIENT_INCLUDE_DIR AND UBIGRAPHCLIENT_LIBRARY)
	SET(UBIGRAPHCLIENT_FOUND 0)
	SET(UBIGRAPHCLIENT_LIBRARIES)
	SET(UBIGRAPHCLIENT_INCLUDE_DIRS)
ENDIF(UBIGRAPHCLIENT_INCLUDE_DIR AND UBIGRAPHCLIENT_LIBRARY)

# Report the results.
IF (NOT UBIGRAPHCLIENT_FOUND)
	SET(UBIGRAPHCLIENT_DIR_MESSAGE
		"ubigraphclient was not found. Make sure UBIGRAPHCLIENT_LIBRARY and UBIGRAPHCLIENT_INCLUDE_DIR are set.")
	IF (NOT UBIGRAPHCLIENT_FIND_QUIETLY)
		MESSAGE(STATUS "${UBIGRAPHCLIENT_DIR_MESSAGE}")
	ELSE (NOT UBIGRAPHCLIENT_FIND_QUIETLY)
		IF (UBIGRAPHCLIENT_FIND_REQUIRED)
			MESSAGE(FATAL_ERROR "${UBIGRAPHCLIENT_DIR_MESSAGE}")
		ENDIF (UBIGRAPHCLIENT_FIND_REQUIRED)
	ENDIF (NOT UBIGRAPHCLIENT_FIND_QUIETLY)
ENDIF (NOT UBIGRAPHCLIENT_FOUND)

MARK_AS_ADVANCED(
	UBIGRAPHCLIENT_INCLUDE_DIR
	UBIGRAPHCLIENT_LIBRARY
)
