# -*- mode: ruby -*-
# # vi: set ft=ruby :

# QuickStart
# 1. vagrant up
# 2. vagrant ssh
#
# Windows note: before running the above commands, you must make sure that 'ssh'
# is in your system path. After downloading 'git', you should go to your control
# panel, and edit your Environment Variables and append the folder containing
# ssh to the system path. For example: C:\Program Files (x86)\Git\bin
#
# TODO:
# 1. Change Ubuntu archive mirror to a local mirror.
# 2. Change vb.customize memory and cpus values as a percentage of host values,
#    or reading from an environment variable that users set.
# 3. Test docker provider.
#
# More documentation @ http://wiki.opencog.org/w/Building_OpenCog#Run_Vagrant

Vagrant.require_version ">= 2.0.0"
Vagrant.configure("2") do |config|
  # Configure the box for opencog development
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "opencog"
  config.vm.provision :shell, inline: "wget -O /tmp/octool \
    https://raw.githubusercontent.com/opencog/ocpkg/master/ocpkg \
     && chmod +rx /tmp/octool"
  config.vm.provision :shell, inline: "/tmp/octool -rdpcav -l default"

  # Port forwarding for REST API
  config.vm.network "forwarded_port", guest: 5000, host: 5000,
    host_ip: "127.0.0.1"

  # Configure port for telnet access to shell
  config.vm.network "forwarded_port", guest: 17001, host: 17001,
    host_ip: "127.0.0.1"

  # Assign a private network ip that can be used for accesing the guest from
  # host.
  config.vm.network "private_network", type: "dhcp"

  # Sync directory containing this Vagrantfile.
  config.vm.synced_folder ".", "/home/vagrant/opencog"
  # Disable the default /vagrant synced directory.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |vb|
      vb.linked_clone = true
      vb.name = "opencog-dev"
      vb.memory = "2048"
      vb.cpus = 1
  end

  # Message displayed on vagrant up
  config.vm.post_up_message = "
  To ssh into the virtual machine run 'vagrant ssh'.

  The virtual machine has all the dependencies required for working on
  cogutil, atomspace, moses, and opencog.

  octool can be found at '/tmp/octool'.

  The folder from which your run 'vagrant up' is accessiable at
  '/home/vagrant/opencog' on sshing into the virtual machine.

  Virtual machine ports 5000 and 17001 are mapped to ports 5000 and 17001
  on your host machine.

  Have fun :-)
  "
end
