(ConceptNode "___PLN___")
(ConceptNode "toy" (stv 1 0))
(ConceptNode "red_bucket_6" (stv 1 0))
(ListLink (stv 1 0) (VariableNode "$t" (stv 1 0)))
(ListLink (stv 1 0) (VariableNode "$AAAAAAAAA" (stv 1 0))
    (ConceptNode "red_bucket_6" (stv 1 0)))
(VariableNode "$t" (stv 1 0))
(VariableNode "$AAAAAAAAA" (stv 1 0))
(ForAllLink (stv 1 0.833) (ListLink (stv 1 0) (VariableNode "$t" (stv 1 0)))
    (ImplicationLink (stv 1 0) (InheritanceLink (stv 1 0) (VariableNode "$AAAAAAAAA" (stv 1 0))
    (ConceptNode "toy" (stv 1 0)))
       (EvaluationLink (stv 1 0) (PredicateNode "found_under" (stv 1 0))
          (ListLink (stv 1 0) (VariableNode "$AAAAAAAAA" (stv 1 0))
             (ConceptNode "red_bucket_6" (stv 1 0))))))
(ImplicationLink (stv 1 0) (InheritanceLink (stv 1 0) (VariableNode "$AAAAAAAAA" (stv 1 0))
    (ConceptNode "toy" (stv 1 0)))
    (EvaluationLink (stv 1 0) (PredicateNode "found_under" (stv 1 0))
       (ListLink (stv 1 0) (VariableNode "$AAAAAAAAA" (stv 1 0))
          (ConceptNode "red_bucket_6" (stv 1 0)))))
(EvaluationLink (stv 1 0) (PredicateNode "found_under" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$AAAAAAAAA" (stv 1 0))
       (ConceptNode "red_bucket_6" (stv 1 0))))
(InheritanceLink (stv 1 0) (VariableNode "$AAAAAAAAA" (stv 1 0))
    (ConceptNode "toy" (stv 1 0)))
(PredicateNode "found_under" (stv 1 0))
