(ConceptNode "___PLN___")
(AndLink (stv 1 0) (FWVariableNode "$ZETW1" (stv 1 0)))
(ImplicationLink (stv 1 0) (FWVariableNode "$ZETW2" (stv 1 0))
    (FWVariableNode "$ZETW1" (stv 1 0)))
(ImplicationLink (stv 1 0.99900001) (AndLink (stv 1 0) (FWVariableNode "$ZETW1" (stv 1 0)))
    (ImplicationLink (stv 1 0) (FWVariableNode "$ZETW2" (stv 1 0))
       (FWVariableNode "$ZETW1" (stv 1 0))))
(FWVariableNode "$ZETW1" (stv 1 0))
(FWVariableNode "$ZETW2" (stv 1 0))
