(ConceptNode "___PLN___")
(AndLink (stv 1 0) (VariableNode "$ZETW1" (stv 1 0)))
(ImplicationLink (stv 1 0) (VariableNode "$ZETW2" (stv 1 0))
    (VariableNode "$ZETW1" (stv 1 0)))
(ImplicationLink (stv 1 0.99900001) (AndLink (stv 1 0) (VariableNode "$ZETW1" (stv 1 0)))
    (ImplicationLink (stv 1 0) (VariableNode "$ZETW2" (stv 1 0))
       (VariableNode "$ZETW1" (stv 1 0))))
(VariableNode "$ZETW1" (stv 1 0))
(VariableNode "$ZETW2" (stv 1 0))
