(ConceptNode "___PLN___")
(ConceptNode "ball" (stv 1 0))
(ListLink (stv 1 0) (EvaluationLink (stv 1 0) (SchemaNode "walktowards" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$2" (stv 1 0)))))
(ListLink (stv 1 0) (VariableNode "$10000" (stv 1 0)))
(ListLink (stv 1 0) (ConceptNode "ball" (stv 1 0)))
(ListLink (stv 1 0) (VariableNode "$AAAAAAAAA" (stv 1 0)))
(ListLink (stv 1 0) (EvaluationLink (stv 1 0) (SchemaNode "walktowards" (stv 1 0))
    (ListLink (stv 1 0) (ConceptNode "ball" (stv 1 0)))))
(ListLink (stv 1 0) (VariableNode "$1" (stv 1 0)))
(ListLink (stv 1 0) (EvaluationLink (stv 1 0) (SchemaNode "lift" (stv 1 0))
    (ListLink (stv 1 0) (ConceptNode "ball" (stv 1 0)))))
(ListLink (stv 1 0) (EvaluationLink (stv 1 0) (SchemaNode "hold" (stv 1 0))
    (ListLink (stv 1 0) (ConceptNode "ball" (stv 1 0)))))
(ListLink (stv 1 0) (VariableNode "$AAAAAAAAB" (stv 1 0)))
(ListLink (stv 1 0) (VariableNode "$obj" (stv 1 0)))
(ListLink (stv 1 0) (VariableNode "$2" (stv 1 0)))
(ListLink (stv 1 0) (EvaluationLink (stv 1 0) (SchemaNode "lift" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$obj" (stv 1 0)))))
(AndLink (stv 1 0) (EvaluationLink (stv 1 0) (PredicateNode "actionTried" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$1" (stv 1 0))))
    (EvaluationLink (stv 1 0) (PredicateNode "can_do" (stv 1 0))
       (ListLink (stv 1 0) (VariableNode "$1" (stv 1 0)))))
(AndLink (stv 1 0) (EvaluationLink (stv 1 0) (PredicateNode "just_done" (stv 1 0))
    (ListLink (stv 1 0) (EvaluationLink (stv 1 0) (SchemaNode "walktowards" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$2" (stv 1 0)))))))
(AndLink (stv 1 0) (EvaluationLink (stv 1 0) (PredicateNode "do" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$1" (stv 1 0))))
    (EvaluationLink (stv 1 0) (PredicateNode "can_do" (stv 1 0))
       (ListLink (stv 1 0) (VariableNode "$1" (stv 1 0)))))
(VariableNode "$10000" (stv 1 0))
(VariableNode "$AAAAAAAAA" (stv 1 0))
(VariableNode "$obj" (stv 1 0))
(VariableNode "$AAAAAAAAB" (stv 1 0))
(ForAllLink (stv 1 0.80000001) (ListLink (stv 1 0) (VariableNode "$obj" (stv 1 0)))
    (ImplicationLink (stv 1 0) (EvaluationLink (stv 1 0) (PredicateNode "near" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$obj" (stv 1 0))))
       (EvaluationLink (stv 1 0) (PredicateNode "can_do" (stv 1 0))
          (ListLink (stv 1 0) (EvaluationLink (stv 1 0) (SchemaNode "lift" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$obj" (stv 1 0))))))))
(ForAllLink (stv 1 0.99900001) (ListLink (stv 1 0) (VariableNode "$10000" (stv 1 0)))
    (EvaluationLink (stv 1 0) (PredicateNode "can_do" (stv 1 0))
       (ListLink (stv 1 0) (VariableNode "$10000" (stv 1 0)))))
(ForAllLink (stv 1 0.99900001) (ListLink (stv 1 0) (VariableNode "$AAAAAAAAB" (stv 1 0)))
    (EvaluationLink (stv 1 0) (PredicateNode "do" (stv 1 0))
       (ListLink (stv 1 0) (VariableNode "$AAAAAAAAB" (stv 1 0)))))
(ForAllLink (stv 1 0.99900001) (ListLink (stv 1 0) (VariableNode "$AAAAAAAAA" (stv 1 0)))
    (EvaluationLink (stv 1 0) (PredicateNode "actionTried" (stv 1 0))
       (ListLink (stv 1 0) (VariableNode "$AAAAAAAAA" (stv 1 0)))))
(ImplicationLink (stv 1 0.99900001) (AndLink (stv 1 0) (EvaluationLink (stv 1 0) (PredicateNode "do" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$1" (stv 1 0))))
    (EvaluationLink (stv 1 0) (PredicateNode "can_do" (stv 1 0))
       (ListLink (stv 1 0) (VariableNode "$1" (stv 1 0)))))
    (EvaluationLink (stv 1 0) (PredicateNode "just_done" (stv 1 0))
       (ListLink (stv 1 0) (VariableNode "$1" (stv 1 0)))))
(ImplicationLink (stv 1 0) (EvaluationLink (stv 1 0) (PredicateNode "near" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$obj" (stv 1 0))))
    (EvaluationLink (stv 1 0) (PredicateNode "can_do" (stv 1 0))
       (ListLink (stv 1 0) (EvaluationLink (stv 1 0) (SchemaNode "lift" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$obj" (stv 1 0)))))))
(ImplicationLink (stv 1 0.99900001) (AndLink (stv 1 0) (EvaluationLink (stv 1 0) (PredicateNode "actionTried" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$1" (stv 1 0))))
    (EvaluationLink (stv 1 0) (PredicateNode "can_do" (stv 1 0))
       (ListLink (stv 1 0) (VariableNode "$1" (stv 1 0)))))
    (EvaluationLink (stv 1 0) (PredicateNode "actionDone" (stv 1 0))
       (ListLink (stv 1 0) (VariableNode "$1" (stv 1 0)))))
(ImplicationLink (stv 1 0.99000001) (EvaluationLink (stv 1 0) (PredicateNode "just_done" (stv 1 0))
    (ListLink (stv 1 0) (EvaluationLink (stv 1 0) (SchemaNode "lift" (stv 1 0))
    (ListLink (stv 1 0) (ConceptNode "ball" (stv 1 0))))))
    (EvaluationLink (stv 1 0) (PredicateNode "can_do" (stv 1 0))
       (ListLink (stv 1 0) (EvaluationLink (stv 1 0) (SchemaNode "hold" (stv 1 0))
    (ListLink (stv 1 0) (ConceptNode "ball" (stv 1 0)))))))
(ImplicationLink (stv 1 0.99900001) (AndLink (stv 1 0) (EvaluationLink (stv 1 0) (PredicateNode "just_done" (stv 1 0))
    (ListLink (stv 1 0) (EvaluationLink (stv 1 0) (SchemaNode "walktowards" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$2" (stv 1 0)))))))
    (EvaluationLink (stv 1 0) (PredicateNode "near" (stv 1 0))
       (ListLink (stv 1 0) (VariableNode "$2" (stv 1 0)))))
(EvaluationLink (stv 1 0) (SchemaNode "walktowards" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$2" (stv 1 0))))
(EvaluationLink (stv 1 0) (PredicateNode "can_do" (stv 1 0))
    (ListLink (stv 1 0) (EvaluationLink (stv 1 0) (SchemaNode "lift" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$obj" (stv 1 0))))))
(EvaluationLink (stv 1 0) (PredicateNode "just_done" (stv 1 0))
    (ListLink (stv 1 0) (EvaluationLink (stv 1 0) (SchemaNode "walktowards" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$2" (stv 1 0))))))
(EvaluationLink (stv 1 0) (PredicateNode "near" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$2" (stv 1 0))))
(EvaluationLink (stv 1 0) (PredicateNode "can_do" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$10000" (stv 1 0))))
(EvaluationLink (stv 1 0) (SchemaNode "walktowards" (stv 1 0))
    (ListLink (stv 1 0) (ConceptNode "ball" (stv 1 0))))
(EvaluationLink (stv 1 0) (PredicateNode "actionTried" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$AAAAAAAAA" (stv 1 0))))
(EvaluationLink (stv 1 0.99000001) (PredicateNode "can_do" (stv 1 0))
    (ListLink (stv 1 0) (EvaluationLink (stv 1 0) (SchemaNode "walktowards" (stv 1 0))
    (ListLink (stv 1 0) (ConceptNode "ball" (stv 1 0))))))
(EvaluationLink (stv 1 0) (SchemaNode "lift" (stv 1 0))
    (ListLink (stv 1 0) (ConceptNode "ball" (stv 1 0))))
(EvaluationLink (stv 1 0) (PredicateNode "actionTried" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$1" (stv 1 0))))
(EvaluationLink (stv 1 0) (PredicateNode "can_do" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$1" (stv 1 0))))
(EvaluationLink (stv 1 0) (PredicateNode "just_done" (stv 1 0))
    (ListLink (stv 1 0) (EvaluationLink (stv 1 0) (SchemaNode "lift" (stv 1 0))
    (ListLink (stv 1 0) (ConceptNode "ball" (stv 1 0))))))
(EvaluationLink (stv 1 0) (SchemaNode "hold" (stv 1 0))
    (ListLink (stv 1 0) (ConceptNode "ball" (stv 1 0))))
(EvaluationLink (stv 1 0) (PredicateNode "actionDone" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$1" (stv 1 0))))
(EvaluationLink (stv 1 0) (PredicateNode "can_do" (stv 1 0))
    (ListLink (stv 1 0) (EvaluationLink (stv 1 0) (SchemaNode "hold" (stv 1 0))
    (ListLink (stv 1 0) (ConceptNode "ball" (stv 1 0))))))
(EvaluationLink (stv 1 0) (PredicateNode "do" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$AAAAAAAAB" (stv 1 0))))
(EvaluationLink (stv 1 0) (PredicateNode "do" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$1" (stv 1 0))))
(EvaluationLink (stv 1 0) (PredicateNode "just_done" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$1" (stv 1 0))))
(EvaluationLink (stv 1 0) (PredicateNode "near" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$obj" (stv 1 0))))
(EvaluationLink (stv 1 0) (SchemaNode "lift" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$obj" (stv 1 0))))
(SchemaNode "walktowards" (stv 1 0))
(SchemaNode "lift" (stv 1 0))
(SchemaNode "hold" (stv 1 0))
(PredicateNode "just_done" (stv 1 0))
(PredicateNode "near" (stv 1 0))
(PredicateNode "can_do" (stv 1 0))
(PredicateNode "actionTried" (stv 1 0))
(PredicateNode "actionDone" (stv 1 0))
(PredicateNode "do" (stv 1 0))
(VariableNode "$2" (stv 1 0))
(VariableNode "$1" (stv 1 0))
