(ConceptNode "BN0" (stv 1 0))
(ConceptNode "CD0" (stv 1 0))
(ConceptNode "Q" (stv 0.89999998 0))
(ConceptNode "Z" (stv 1 0))
(ConceptNode "___PLN___")
(ConceptNode "A" (stv 1 0))
(ConceptNode "B" (stv 1 0))
(ConceptNode "C" (stv 1 0))
(SubsetLink (stv 1 0) (VariableNode "$AAAAAAAEN" (stv 1 0))
    (VariableNode "$AAAAAAAEO" (stv 1 0)))
(SubsetLink (stv 1 0) (VariableNode "$AAAAAAAEO" (stv 1 0))
    (VariableNode "$Z" (stv 1 0)))
(SubsetLink (stv 1 0) (VariableNode "$AAAAAAAEN" (stv 1 0))
    (VariableNode "$Z" (stv 1 0)))
(SubsetLink (stv 1 0) (VariableNode "$AAAAAAAEP" (stv 1 0))
    (VariableNode "$XS" (stv 1 0)))
(SubsetLink (stv 1 0) (VariableNode "$AAAAAAAEP" (stv 1 0))
    (VariableNode "$ZS" (stv 1 0)))
(SubsetLink (stv 1 0) (VariableNode "$AAAAAAAER" (stv 1 0))
    (VariableNode "$AAAAAAAER" (stv 1 0)))
(ListLink (stv 1 0) (VariableNode "$AAAAAAAEN" (stv 1 0))
    (VariableNode "$AAAAAAAEO" (stv 1 0))
    (VariableNode "$Z" (stv 1 0)))
(ListLink (stv 1 0) (VariableNode "$AAAAAAAEP" (stv 1 0))
    (VariableNode "$XS" (stv 1 0))
    (VariableNode "$YS" (stv 1 0))
    (VariableNode "$ZS" (stv 1 0)))
(ListLink (stv 1 0) (VariableNode "$ZS" (stv 1 0))
    (VariableNode "$XS" (stv 1 0))
    (VariableNode "$YS" (stv 1 0)))
(ListLink (stv 1 0) (VariableNode "$AAAAAAAEQ" (stv 1 0)))
(ListLink (stv 1 0) (VariableNode "$AAAAAAAER" (stv 1 0)))
(ListLink (stv 1 0) (VariableNode "$X" (stv 1 0))
    (VariableNode "$Y" (stv 1 0)))
(AndLink (stv 1 0) (SubsetLink (stv 1 0) (VariableNode "$AAAAAAAEN" (stv 1 0))
    (VariableNode "$AAAAAAAEO" (stv 1 0)))
    (SubsetLink (stv 1 0) (VariableNode "$AAAAAAAEO" (stv 1 0))
       (VariableNode "$Z" (stv 1 0))))
(AndLink (stv 0.44999999 0) (ConceptNode "BN0" (stv 1 0))
    (ConceptNode "CD0" (stv 1 0)))
(AndLink (stv 0.333 0) (ConceptNode "C" (stv 1 0))
    (ConceptNode "Q" (stv 0.89999998 0))
    (ConceptNode "Z" (stv 1 0)))
(AndLink (stv 1 0) (SubsetLink (stv 1 0) (VariableNode "$AAAAAAAEP" (stv 1 0))
    (VariableNode "$XS" (stv 1 0)))
    (EvaluationLink (stv 1 0) (PredicateNode "union" (stv 1 0))
       (ListLink (stv 1 0) (VariableNode "$ZS" (stv 1 0))
          (VariableNode "$XS" (stv 1 0))
          (VariableNode "$YS" (stv 1 0)))))
(AndLink (stv 1 0) (VariableNode "$X" (stv 1 0))
    (VariableNode "$Y" (stv 1 0)))
(AndLink (stv 1 0) (VariableNode "$Y" (stv 1 0))
    (VariableNode "$X" (stv 1 0)))
(VariableNode "$AAAAAAAEP" (stv 1 0))
(VariableNode "$XS" (stv 1 0))
(VariableNode "$YS" (stv 1 0))
(VariableNode "$ZS" (stv 1 0))
(VariableNode "$AAAAAAAEQ" (stv 1 0))
(VariableNode "$AAAAAAAER" (stv 1 0))
(VariableNode "$X" (stv 1 0))
(VariableNode "$Y" (stv 1 0))
(VariableNode "$AAAAAAAEN" (stv 1 0))
(VariableNode "$AAAAAAAEO" (stv 1 0))
(VariableNode "$Z" (stv 1 0))
(ImplicationLink (stv 1 0) (AndLink (stv 1 0) (SubsetLink (stv 1 0) (VariableNode "$AAAAAAAEN" (stv 1 0))
    (VariableNode "$AAAAAAAEO" (stv 1 0)))
    (SubsetLink (stv 1 0) (VariableNode "$AAAAAAAEO" (stv 1 0))
       (VariableNode "$Z" (stv 1 0))))
    (SubsetLink (stv 1 0) (VariableNode "$AAAAAAAEN" (stv 1 0))
       (VariableNode "$Z" (stv 1 0))))
(ImplicationLink (stv 1 0) (AndLink (stv 1 0) (SubsetLink (stv 1 0) (VariableNode "$AAAAAAAEP" (stv 1 0))
    (VariableNode "$XS" (stv 1 0)))
    (EvaluationLink (stv 1 0) (PredicateNode "union" (stv 1 0))
       (ListLink (stv 1 0) (VariableNode "$ZS" (stv 1 0))
          (VariableNode "$XS" (stv 1 0))
          (VariableNode "$YS" (stv 1 0)))))
    (SubsetLink (stv 1 0) (VariableNode "$AAAAAAAEP" (stv 1 0))
       (VariableNode "$ZS" (stv 1 0))))
(ImplicationLink (stv 1 0) (VariableNode "$AAAAAAAEQ" (stv 1 0))
    (VariableNode "$AAAAAAAEQ" (stv 1 0)))
(ImplicationLink (stv 1 0) (ConceptNode "C" (stv 1 0)))
(ImplicationLink (stv 1 0) (AndLink (stv 1 0) (VariableNode "$X" (stv 1 0))
    (VariableNode "$Y" (stv 1 0)))
    (AndLink (stv 1 0) (VariableNode "$Y" (stv 1 0))
       (VariableNode "$X" (stv 1 0))))
(EvaluationLink (stv 1 0) (PredicateNode "union" (stv 1 0))
    (ListLink (stv 1 0) (VariableNode "$ZS" (stv 1 0))
       (VariableNode "$XS" (stv 1 0))
       (VariableNode "$YS" (stv 1 0))))
(PredicateNode "union" (stv 1 0))
