# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-7.3

# Local packages, usually specified by relative directory name
packages:
- '.'
- location:
   git: https://github.com/rTreutlein/invertible-syntax
   commit: 2fbc868a9e74f27eac0f856326385d654455fc0b
- location:
   git: https://github.com/rTreutlein/partial-isomorphisms
   commit: a8d1b86de0a1e1a85c20a25937f50a173b0a990d

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: [opencog-atomspace-0.1.0.7]

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.10.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
extra-lib-dirs: [/usr/local/lib/opencog]
