
(define-module (opencog nlp fuzzy))

(use-modules (srfi srfi-1)
             (opencog)
             (opencog query)  ; for cog-fuzzy-match
             (opencog nlp)
             (opencog nlp sureal)
             (opencog nlp microplanning))

; ----------------------------------------------------------
(define-public (get-answers sent-node)
"
  Find answers (i.e., similar sentences that share some keyword) from
  the Atomspace by using the fuzzy pattern matcher. By default, it
  excludes sentences with TruthQuerySpeechAct and InterrogativeSpeechAct.

  Accepts a SentenceNode as the input.
  Returns one or more sentence strings -- the answers.

  For example:
     (get-answers (car (nlp-parse \"What did Pete eat?\")))
  OR:
     (get-answers (SentenceNode \"sentence@123\"))

  Possible result:
     (Pete ate apples .)
"
    (sent-matching sent-node
        (list (DefinedLinguisticConceptNode "TruthQuerySpeechAct")
              (DefinedLinguisticConceptNode "InterrogativeSpeechAct")))
)

; ----------------------------------------------------------
(define-public (sent-matching sent-node exclude-list)
"
  The main function for finding similar sentences
  Returns one or more sentences that are similar to the input one but
  contain no atoms that are listed in the exclude-list.
"
    ; Generate sentences from each of the R2L-SetLinks
    ; (define (generate-sentences r2l-setlinks) (if (> (length r2l-setlinks) 0) (map sureal r2l-setlinks) '()))

    ; Generate sentences for each of the SetLinks found by the fuzzy matcher
    ; TODO: May need to filter out some of the contents of the SetLinks
    ; before sending each of them to Microplanner

    (define (generate-sentences setlinks)

        ; Find the speech act from the SetLink and use it for Microplanning
        (define (get-speech-act setlink)
            (let* ((speech-act-node-name
                        (filter (lambda (name)
                            (if (string-suffix? "SpeechAct" name) #t #f))
                                (map cog-name (cog-filter 'DefinedLinguisticConceptNode (cog-get-all-nodes setlink))))))

                ; If no speech act was found, return "declarative" as default
                (if (> (length speech-act-node-name) 0)
                    (string-downcase (substring (car speech-act-node-name) 0 (string-contains (car speech-act-node-name) "SpeechAct")))
                    "declarative"
                )
            )
        )
(trace-msg "duuude whhhhhhhhhhhhhhhhhhhhhhhh\n")

(trace-msg "duuude setlinks  is ")
(trace-msg setlinks)
        (append-map (lambda (r)
            ; Send each of the SetLinks found by the fuzzy matcher to
            ; Microplanner to see if they are good
            (let* ( (spe-act (get-speech-act r))
                    (seq-and (SequentialAndLink (cog-outgoing-set r)))
                    (m-results (microplanning seq-and spe-act
                         *default_chunks_option* #f)))
(trace-msg "duuude sp-act is ")
(trace-msg seq-and)
                ; Don't send it to SuReal in case it's not good
                ; (i.e. Microplanner returns #f)
                (if m-results
                    (append-map
                        ; Send each of the SetLinks returned by
                        ; Microplanning to SuReal for sentence generation
                        (lambda (m) (sureal (car m)))
                        m-results
                    )
                    '()
                )
            ))
            setlinks
        )
    )

    (let* ( ; parse is the ParseNode for the sentence
            (parse (car (cog-chase-link 'ParseLink 'ParseNode sent-node)))

            ; intrp is the InterpretationNode for the sentence
            (intrp (car (cog-chase-link 'InterpretationLink 'InterpretationNode parse)))
            ; setlk is the R2L SetLink of the input sentence
            (setlk (car (cog-chase-link 'ReferenceLink 'SetLink intrp)))

            ; fzset is the set of similar sets.
            (fzset (cog-fuzzy-match setlk 'SetLink exclude-list))

            ; reply is the generated reply sentences.
            ; generated by  Microplanner and SuReal
            (reply (generate-sentences (cog-outgoing-set fzset)))
        )
(trace-msg "duuude setk is ")
(trace-msg setlk)
(trace-msg "duuude fuzz  is ")
(trace-msg fzset)

(trace-msg "duuude gens  is ")
(trace-msg reply)

        ; Delete identical sentences from the return set
        (delete-duplicates reply)
    )
)
