(InheritanceLink (stv 1.0 1.0)
   (PredicateNode "no_Answer")
   (DefinedFrameNode "#Answer")
)
(InheritanceLink (stv 1.0 1.0)
   (PredicateNode "no_Answer_Message")
   (DefinedFrameElementNode "#Answer:Message")
)
(FrameElementLink (stv 1.0 1.0)
   (PredicateNode "no_Answer")
   (PredicateNode "no_Answer_Message")
)
(EvaluationLink (stv 1.0 1.0)
   (PredicateNode "no_Answer_Message")
   (WordInstanceNode "no")
)
(EvaluationLink (stv 1.0 1.0)
   (PredicateNode "latestQuestionFrames")
   (ListLink
      (PredicateNode "no_Answer")
   )
)
