
; DO NOT EDIT THIS FILE!  This file was automatically
; generated from atom definitions in types.script
;
; This file contains basic scheme wrappers for atom creation.
;
(define (SavingLoadingTestLink . x)
	(apply cog-new-link (append (list 'SavingLoadingTestLink) x)))
(define (SavingLoadingTestNode . x)
	(apply cog-new-node (append (list 'SavingLoadingTestNode) x)))
